### PR TITLE
Reverse the order of episodes. Closes #50

### LINKED ISSUE #50: Invert order of past episodes list
I think it’s more common to show more recent episodes/posts/whatever first in this kind of lists. And since you removed dates it the new design it’s harder to undrestand that the list is reversed.

### PR DESCRIPTION
**Pull request by sotojuan**
I think this should do it! I'm a bit confused by [this](https://github.com/javascriptair/site/issues/50#issuecomment-196458375) comment though—the function does pass the index, right? I can give it a shot though.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hi @sotojuan! Thanks for contributing! Two things:
1. Looks like the build had trouble with the `reverse` function. You might be able to just call `.reverse` on it instead.
2. Could you add yourself to [the contributors data](https://github.com/javascriptair/site/blob/f98a36b2a227259baab38de4ae819137e8cc6861/data/contributors/index.js) for that page as part of this PR? Let me know if you need help with this :-)

**Comment by kentcdodds** [comment]
Oh, as as for that comment, I want to be able to display the index (which is the episode number) on the page. So it should look something like:

screen shot 2016-03-14 at 1 07 08 pm

**Comment by kentcdodds** [comment]
Except it'd be reversed of course :-)

**Comment by kentcdodds** [comment]
If you'd prefer to do that bit in a separate PR (or leave it to someone else to do) that's fine :D

**Comment by sotojuan** [comment]
I'll just do the `reverse` for now, someone else can step in for the rest :-)

**Comment by kentcdodds** [comment]
Looks awesome! Thanks!

**Comment by kentcdodds** [comment]
Feel free to open another PR to add yourself to the [contributors page](http://javascriptair.com/contributors).

**Comment by sotojuan** [comment]
Sure, what would be my description?

**Comment by kentcdodds** [comment]
How about `Site PRs` or something like that :-)

**Comment by kentcdodds** [comment]
I really should implement something like [all-contributors](https://github.com/kentcdodds/all-contributors) and use emoji instead. So much to do :-)

**Comment by kentcdodds** [comment]
By the way, I just added documentation on how to do images properly in this project: https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#images

Thanks!

**Pull request merged**
