### PR TITLE
Formatted footer, added bootstrap and links (github, code of conduct and contributor links) Closes #123

### LINKED ISSUE #123: Add GitHub link to javascriptair.com
[javascriptair/site](https://github.com/javascriptair/site) isn't mentioned on [javascriptair.com](https://javascriptair.com/). 

At the very least, I think it should be added to the footer :+1: 

I hope that doing so will draw some new contributors. 

Whaddaya think?

### PR DESCRIPTION
**Pull request by housseindjirdeh**
Closes #123

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome @hdjirdeh. I'm looking forward to looking at this more closely.

I must apologize that I didn't make one thing very clear. I mentioned that we don't have a grid system like bootstrap for the site, but I didn't explain that I don't want to add it either. I want to keep the sight as lightweight as possible (hence generating it in the build and serving static files via a CDN). The payload for each page is pretty small.

Is there any way that you could implement this using flexbox?

**Comment by housseindjirdeh** [comment]
Ah sorry about that, for some reason I thought you mentioned to use bootstrap.  

Yeah for sure I'll change it up and try to use flexbox instead :+1:

**Comment by kentcdodds** [comment]
Thanks! And again, sorry about that.

Also, you may want to rebase your branch onto master. I just pushed a bunch of changes. Here's a good way to keep your local copy in sync with the original repo: https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository?course=how-to-contribute-to-an-open-source-project-on-github

**Comment by housseindjirdeh** [comment]
No worries at all, and thanks for the video! Yeah I'll rebase my branch more often (noticed there was a conflict too)

I'll update this PR by tomorrow :)

**Comment by housseindjirdeh** [comment]
@kentcdodds : fixed, take a look whenever you get the chance and let me know if I should change anything :+1:

**Comment by kentcdodds** [comment]
Could you take a few quick screenshots of the different sizes and put them in here?

**Comment by kentcdodds** [comment]
Code looks great!

**Comment by housseindjirdeh** [comment]
Sure thing, and thanks man appreciate it :)

**Comment by housseindjirdeh** [comment]
Laptop: 
laptop

**Comment by housseindjirdeh** [comment]
Mid-size: 
tablet

Mobile:
mobile

**Comment by kentcdodds** [comment]
Wow, this is perfect! Thanks!

**Comment by housseindjirdeh** [comment]
@kentcdodds Literally just stumbled on this article that you wrote a while back https://medium.com/@kentcdodds/how-getting-into-open-source-has-been-awesome-for-me-8480cd756a80#.owygt372l

Drawing parallels here but this was my first contribution to OSS, so thanks for all the help buddy :smile:

**Comment by kentcdodds** [comment]
That's awesome! And you're on [the contributors page](https://javascriptair.com/contributors/) now! Welcome to the wonderful world of OSS!!! 🎉

**Comment by bookercodes** [comment]
Awesome work, @hdjirdeh!

_:gem: :sparkles: Welcome to OSS :sparkles: :gem:_

**Pull request merged**
