### PR TITLE
Added customStyles to Person component

### PR DESCRIPTION
**Pull request by elderfo**
- Added customStyles prop to Person
  - Manually populated via assignment on the props in host/panelists. (This should be done from a structure higher in the tree)
- Moved person style config to a field in render

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome! Could show some screenshots?

**Comment by kentcdodds** [comment]
Oh, and don't forget to [add yourself to the contributors page](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#add-yourself-to-the-contributors-page)

**Comment by elderfo** [comment]
Screenshots? Apologies, this is my first time contrib to a project that is not my own...

**Comment by kentcdodds** [comment]
Yeah, like this:

screen shot 2016-11-04 at 1 02 47 pm

So I can see what it looks like without having to pull it down. If that's alright :)

Here's how you can do it [on mac](https://support.apple.com/en-us/HT201361) and [windows](https://support.microsoft.com/en-us/help/13776/windows-use-snipping-tool-to-capture-screenshots)

**Comment by elderfo** [comment]
Like this?

Before:
screen shot 2016-11-04 at 2 15 28 pm

After: 
screen shot 2016-11-04 at 2 13 38 pm

**Comment by kentcdodds** [comment]
Yes! That's great!

A few things. Could you center the host photo?

And there should be padding between the photos and the name/twitter handle (as it is in the before screenshot). Thanks!

**Comment by elderfo** [comment]
I missed that, I will get that taken care of.

**Comment by elderfo** [comment]
Before:
screen shot 2016-11-04 at 2 13 38 pm

After: 
screen shot 2016-11-04 at 4 14 16 pm

*\* Looks like it fixed the sorting issue too

**Comment by kentcdodds** [comment]
LGTM!

**Comment by kentcdodds** [comment]
Thank you so much!

**Comment by elderfo** [comment]
Thanks for helping me through my first PR!

**Pull request merged**
