### PR TITLE
updated list of contributors

### PR DESCRIPTION
**Pull request by da-vaibhav**
adding myself to the list of contributors

### CODE REVIEW

**Comment by kentcdodds** [comment]
Two things:
1. Looks like this has a merge conflict with upstream. Do you mind [rebasing your branch](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?series=how-to-contribute-to-an-open-source-project-on-github)?
2. Could you use an image that's at least 180x180? Also, please optimize it following [these instructions](https://github.com/javascriptair/site/blob/08ed6c0c8a9e035d506150ba3325ca5bfdef63b6/CONTRIBUTING.md#images)

Thanks!

**Comment by da-vaibhav** [comment]
done!

**Comment by kentcdodds** [comment]
Looks like the image you're using is pretty small. Do you have a bigger one? It'll probably be fine, but I think a bigger one would be better.

**Comment by da-vaibhav** [comment]
oops, I missed some things, updating again.

**Comment by kentcdodds** [comment]
Perfect!

**Pull request merged**
