### PR TITLE
Fixing inconsistencies with dependency versions

### PR DESCRIPTION
**Pull request by camilleriluke**
Issue reproduced only when using `npm` (when using `yarn` everything just works).

Related to: https://github.com/javascriptair/site/pull/170

### CODE REVIEW

**Comment by camilleriluke** [comment]
Please let me know if everything is ok from your perspective. 

It took me some time to figure out how everything ties up together but I think this update will solve the problem I encountered ✌️

**Comment by kentcdodds** [comment]
Any chance we could just update all version ranges to the latest, then update the yarn lock file?

**Comment by kentcdodds** [comment]
I want to keep the ^ if we can

**Comment by kentcdodds** [comment]
Thank you!

**Pull request merged**
