### PR TITLE
Episode 26 - Link fix

### PR DESCRIPTION
**Pull request by camilleriluke**
Updated the "Midwest Dev Chat Slack" link which is currently pointing to `https://javascriptair.com/episodes/2016-06-08/www.midwestdevchat.com`.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thank you! I'm definitely planning on merging. Before I do, would you like to also add yourself to the contributors page? https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#add-yourself-to-the-contributors-page

**Comment by kentcdodds** [comment]
Thanks a bunch!

**Comment by camilleriluke** [comment]
On another note, I had some problems while running `npm start validate`

I used `npm` to install dependencies. However when I used `yarn` everything worked fine.

One way I managed to solve this is by changing all the npm dependencies versions to the specific version (removing all the `^` from the dependencies version).  

I can submit another PR with that change if you wish, but I don't know if you have anything else in mind.

---

Debug info:

```
➜  javascript-air-site git:(master) npm start validate

> javascriptair.com@1.0.0 start /trees/javascript-air-site
> nps "validate"

nps executing: nps build
nps executing: nps -p eslint,build.home,build.episodes,build.guests,build.links-tips-picks,build.deals,build.css,build.contributors,createJson,build.screenshot.all
nps executing: eslint .
nps executing: babel-node generate/home
nps executing: babel-node ./scripts/build-episodes
nps executing: rimraf guests && mkdir guests && babel-node generate/guests
nps executing: rimraf links-tips-picks && mkdir links-tips-picks && babel-node generate/links-tips-picks
nps executing: rimraf deals && mkdir deals && babel-node generate/deals
nps executing: postcss -u postcss-import -u postcss-nested -u postcss-mixins -u autoprefixer -u cssnano resources/css/styles.css > styles.dist.css
nps executing: rimraf contributors && mkdir contributors && babel-node generate/contributors
nps executing: babel-node generate/json-files
nps executing: babel-node ./scripts/screenshot-episodes
server listening at: http://localhost:8899
with a root at: /trees/javascript-air-site
Episodes done building 😎

/trees/javascript-air-site/data/deals/index.js
  2:24  error  Unable to resolve path to module '<utils>/utils'  import/no-unresolved

/trees/javascript-air-site/episodes/2016-01-20/index.js
  2:23  error  Unable to resolve path to module '<resources>/panelists'  import/no-unresolved

/trees/javascript-air-site/episodes/index.js
  4:28  error  Unable to resolve path to module '<utils>/get-episode-data'  import/no-unresolved

.... more like the above errors




The script called "eslint" which runs "eslint ." failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.0.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "build" which runs "nps -p eslint,build.home,build.episodes,build.guests,build.links-tips-picks,build.deals,build.css,build.contributors,createJson,build.screenshot.all" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.0.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "validate" which runs "nps build" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.0.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code

pm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "validate"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! javascriptair.com@1.0.0 start: `nps "validate"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascriptair.com@1.0.0 start script 'nps "validate"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the javascriptair.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nps "validate"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs javascriptair.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls javascriptair.com
npm ERR! There is likely additional logging output above.
```

```
➜  javascript-air-site git:(master) npm -v
3.10.8
➜  javascript-air-site git:(master) node -v
v6.9.1
➜  javascript-air-site git:(master)
```

**Comment by kentcdodds** [comment]
Thanks for letting me know. Could you show me more of the output? The output you gave me doesn't show the real problem.

**Comment by camilleriluke** [comment]
Updated comment above.

**Comment by kentcdodds** [comment]
Interesting... My guess is there's a bug with [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import) or [`eslint-import-resolver-babel-module`](https://github.com/tleunen/eslint-import-resolver-babel-module)

cc @tleunen and @benmosher, do either of you think there have been any recent changes that would cause issues like this?

**Comment by tleunen** [comment]
Indeed, I messed up a few versions :/
Please upgrade to the latest babel-plugin-module-resolver (2.3.0) and latest eslint-import-resolver-babel-module (2.2.1)

**Comment by kentcdodds** [comment]
Thanks @tleunen!

@camilleriluke, would you like to make a PR that bumps the version ranges for those two deps? :)

**Pull request merged**
