### PR TITLE
Add clearer image compression instructions. Closes #59

### LINKED ISSUE #59: Clearer image compressing instructions
It would be nice to add something like this [this section](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#images):

> After you get your resized image (should have your original filename with "resized" in the middle), you can delete your original image and rename the compressed one to the original filename. Essentially, you're replacing the original with the compressed one.

Could be written a little less verbose, but you get the point. Can do this in a PR!

Alternatively, we can discuss changing the behavior of `imagina` to overwrite the original image.

### PR DESCRIPTION
**Pull request by sotojuan**
Let me know if it can be worded better.

### CODE REVIEW

**Comment by kentcdodds** [comment]
One other thing to note is if it's not a PNG, you'll actually have another image representing the resized image, but in the original format. Probably should just delete that one in the script though....

**Comment by kentcdodds** [comment]
Probably a better way to say this is that it ends in `resized.png` which will apply in either case.

**Comment by sotojuan** [comment]
Let me know if there's anything else I should make note of.

**Comment by kentcdodds** [comment]
Thanks :+1:

**Pull request merged**
