### PR TITLE
Initial podcastify version

### PR DESCRIPTION
**Pull request by kentcdodds**
This adds the `podcastify` cli that I'm looking for in #78! Just run `npm run podcastify` and you'll be prompted to choose an episode, then it'll download the audio to your desktop!

Things that are missing (why this isn't merged yet):
- [ ] Convert the stereo output to mono (preserving both left and right, and just merging it to mono)
- [ ] Normalize the audio

The metadata thing isn't super important, but I really would like to have that as well. I'd prefer those to be questions that are asked while the episode is being downloaded if possible.

Would love to get some help to finish this up!

### CODE REVIEW

**Comment by akupila** [comment]
To normalize the audio first analyze a couple minutes of it to get the audio level then use an audio filter to boost the gain. For instance analyze 5 minutes, starting 10min into the show:

```
ffmpeg -i <input.mp3> -ss 00:10:00.00 -t 00:05:00.00 -af "volumedetect" -f null /dev/null
```

Look for `mean_volume: -15.1 dB` in the output (stderr)

Then you can combine stereo channels to mono, apply an audio filter to boost gain for normalizing, add metadata and compress to 128k (96k might be enough):

```
ffmpeg -i <input.mp3> -acodec mp3 -ab 128k -ac 1 -af "volume=15.1dB" -id3v2_version 3 -write_id3v1 1 -metadata title="JavaScript Frameworks: Vue.js" -metadata artist="JavaScript Air" -metadata year=2016 <output.mp3>
```

_edit (in case somebody sees this later): **max_volume**, not **mean_volume**! otherwise you'll blow some eardrums.._

**Comment by kentcdodds** [comment]
Boom!

podcastify

Thank you for the help @akupila and @sduquej! This is really seriously going to save me a bunch of time every week :-)

**Comment by kentcdodds** [comment]
You'll notice in the gif that the progress bar bumps around a bit. If you're interested, I'd love a PR to fix that :-)

**Comment by sduquej** [comment]
awesome! I was about to push some changes, but you've covered it already.

**Comment by kentcdodds** [comment]
Thanks! There are more opportunities to contribute if you're interested. You might check out: https://github.com/javascriptair/site/issues/80

**Pull request merged**
