### PR TITLE
fix(a11y): color-contrast as per AAA guidelines

### LINKED ISSUE #118: Improve the color contrast on the home page links
The color contrast here is really bad:

screen shot 2016-06-15 at 2 54 47 pm

The colors come from [this code](https://github.com/javascriptair/site/blob/601ea1e7276af2a02f67db5d5bb3e0d92382fb1a/src/pages/home/sections/episodes/episode-small.js#L77)

Thanks!

### PR DESCRIPTION
**Pull request by sarbbottam**
for episodes guest links and text

screen_shot_2016-06-15_at_5_29_33_pm

fixes #118

### CODE REVIEW

**Comment by sarbbottam** [comment]
Current color contrast of guest links and text w.r.t the background color, satisfies AAA criteria. Please review.

**Comment by kentcdodds** [comment]
LGTM

**Comment by kentcdodds** [comment]
Thank you! Do you want to add yourself to the contributors page?

**Comment by sarbbottam** [comment]
Thanks for asking, I would certainly in the next fix 😄

**Pull request merged**
