### PR TITLE
added svg icons

### PR DESCRIPTION
**Pull request by bookercodes**
Hey @kentcdodds. Merry christmas eve :santa: 

I am submitting this pull request ahead of time so I can get your comments before moving forward. 

Is this what you were thinking of when you suggested that I use React components to hold the SVG icons?
## Todo
- [ ] Remove now-defunct icon fonts.
- [ ] Style the icons.
- [ ] Improve accessibility using a [`title`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) description string.
- [ ] Possibly move the icons into separate files and load them in using `fs` or something.

### CODE REVIEW

**Comment by bookercodes** [comment]
Another question: 

Should I just slap a class on the icons and style them via _`styles.css`_, or should I do so via the `props` argument?

Thanks!

**Comment by kentcdodds** [comment]
I think that's great. Continue :D Thanks!

**Comment by kentcdodds** [comment]
I like the class approach I think... What do you think would be better?

**Comment by bookercodes** [comment]
@kentcdodds,

 Thanks for the feedback. I had intended to resume work on this today but now think it best to wait until our call tomorrow with @Connorelsea before proceeding.

**Pull request closed without merging**
