### PR TITLE
Added Pocketcasts link

### PR DESCRIPTION
**Pull request by jamesmcallister**
I thought this might help.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Cool! Thanks! Two things:
1. Could you take a screenshot of what this looks like?
2. Could you [add yourself as a contributor](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#add-yourself-to-the-contributors-page) as part of this PR?

Thanks!

**Comment by jamesmcallister** [comment]
screenshot_20160908_200814

Done.

**Comment by kentcdodds** [comment]
Awesome! Could you please show me whether this is responsive as well? Take screenshots at different screen widths? Thanks!

**Comment by jamesmcallister** [comment]
I have changed a couple of widths from '%' to 'px', to keep cross device conformity.

Only there where 3 icons on the top line and one on the bottom line, it was really bugging me.

screenshot_20160908_222936
screenshot_20160908_222948
screenshot_20160908_223010
screenshot_20160908_223057

**Comment by kentcdodds** [comment]
Fantastic! Thank you! 👏

**Pull request merged**
