### PR TITLE
Add myself to contributors list

### PR DESCRIPTION
**Pull request by sotojuan**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome @sotojuan! Looking forward to adding you! Do you mind following [these instructions](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#images) to optimize the image?

**Comment by sotojuan** [comment]
I'm pretty sure I did that, but I'll run it again just to make sure.

**Comment by kentcdodds** [comment]
Ok, great. The tool wont replace the existing image, just create a new one with `.resized.png` appended to the filename. And the image will be `180x180`

**Comment by sotojuan** [comment]
So I just commit that resized image? Or delete the original and rename the compressed one?

**Comment by kentcdodds** [comment]
> delete the original and rename the compressed one?

Yes :-)

**Comment by kentcdodds** [comment]
Sorry, the reason it's that way is because when I built the tool I thought that it'd be better to not be destructive so instead of overwriting, I just made a copy. Maybe I should have renamed the old one or something. :-)

**Comment by sotojuan** [comment]
It's fine! Just did it.

**Comment by kentcdodds** [comment]
Perfect!

**Pull request merged**
