### PR TITLE
added util class randomize

### PR DESCRIPTION
**Pull request by timarney**
Issue #96

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hey @timarney! This is great. I apologize, but I think that it'd probably just be better to change `sortPeople` to use `_.shuffle`. And then leave everything else as it is. Thoughts? I don't think that there's anywhere we use `sortPeople` that we wouldn't just want them randomized.

**Comment by timarney** [comment]
No problem ...
So your thinking:

```
function sortPeople(people = []) {
  return shuffle(people)
}
```

and 

```
const nonFinancialContributors = sortPeople([host, ...panelistContributors, ...contributors])
```

yes?

**Comment by kentcdodds** [comment]
How about in the `export` statement in `utils` we just do:

``` javascript
export {
  displayListify, intersperse,
  isPast, isFuture, isToday, isPastAndNotToday, shuffle as sortPeople,
  markdownToHTML, getClassNames,
  getRandomPositiveEmoji,
}
```

And then yes to the `nonFinancialContributors` portion

**Comment by timarney** [comment]
Nice - good call :)

**Comment by timarney** [comment]
Did a rebase / squash - hopefully I got that right this time :)

**Comment by kentcdodds** [comment]
This is perfect! Thanks

**Comment by bookercodes** [comment]
Nice work, @timarney :smile:

**Pull request merged**
