### PR TITLE
Aphrodite-ize the episode cards. Closes #124

### LINKED ISSUE #124: Aphrodite-ize the episode cards
I've been working on this for a while and it's getting close. If someone wants to pick it up and finish it that'd be awesome. I think that all that's left is to do the [calendar.js](https://github.com/javascriptair/site/blob/9b8572d5e167bde471acb29ca3831cf590cf7c93/src/pages/home/sections/episodes/episode/calendar.js) file. The current styles for this file live [here](https://github.com/javascriptair/site/blob/9b8572d5e167bde471acb29ca3831cf590cf7c93/resources/css/episode.css).

The real challenge here is that aphrodite doesn't officially support descendant selection of pseudo-states like we're doing [here](https://github.com/javascriptair/site/blob/9b8572d5e167bde471acb29ca3831cf590cf7c93/resources/css/episode.css#L20-L53) (more info [here](https://github.com/Khan/aphrodite/issues/10)). We could probably employ [the current workaround](https://github.com/Khan/aphrodite/issues/10#issuecomment-151932496) for now and I'll come back later to clean it up when that's properly supported.

If anyone wants to pick this up, I'd be much obliged :D

Don't forget to [add yourself](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#add-yourself-to-the-contributors-page) to [the contributors page](https://javascriptair.com/contributors/) if this is your first contribution :+1:

### PR DESCRIPTION
**Pull request by anthwinter**

### CODE REVIEW

**Comment by anthwinter** [comment]
I am not sure if the :hover styling is the best way to go about things, but the way I have implemented is the only way I could think of referencing the child classes (e.g. [class^=...])

Also, I am not sure about the merge problems it notified me about. If there is anything I can do to fix those, let me know 🙂

**Comment by kentcdodds** [comment]
Cool! I look forward to pulling this down! If you want to fix the merge problems, then you'll need to rebase this with master. See [this](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?course=how-to-contribute-to-an-open-source-project-on-github)

Thanks!

**Comment by anthwinter** [comment]
Ah ok. First rebase... Hopefully that worked.

**Comment by kentcdodds** [comment]
Worked great! I'll give this a look as soon as I'm able. Thanks again!

**Comment by kentcdodds** [comment]
Oh, and if you want, you can add yourself to the contributors page in this PR. See the contributing guidelines.

**Comment by anthwinter** [comment]
Have done 👍 Thanks

**Comment by kentcdodds** [comment]
Just tried it out and it looks perfect! Thanks a ton :D

**Pull request merged**
